// ==UserScript==
// @name         Soda(qishui) Music Download
// @name:zh-CN   汽水音乐下载
// @namespace    https://github.com/
// @author       ChangJin Wei (魏昌进)
// @license      Apache-2.0
// @version      2026.614.12317
// @description  Add a download button to Qishui share track pages.
// @description:zh-CN 在汽水音乐分享页添加立即下载按钮。
// @homepageURL  https://github.com/galaxy-sea/Soda-Music-Download
// @supportURL   https://github.com/galaxy-sea/Soda-Music-Download/issues
// @updateURL    https://raw.githubusercontent.com/galaxy-sea/Soda-Music-Download/main/userscript/qishui-download.user.js
// @downloadURL  https://raw.githubusercontent.com/galaxy-sea/Soda-Music-Download/main/userscript/qishui-download.user.js
// @match        https://music.douyin.com/qishui/share/track*
// @match        https://www.qishui.com/share/track*
// @run-at       document-start
// @grant        GM_download
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_openInTab
// @grant        unsafeWindow
// @connect      *
// ==/UserScript==

// This file is generated by build-userscript.sh. Edit the template and shared files instead.
(function () {
  "use strict";

(function (globalScope) {
  "use strict";

  const DOWNLOAD_BUTTON_ID = "soda-music-download-button";
  const DEFAULT_MAX_ATTEMPTS = 120;
  const DEFAULT_INTERVAL_MS = 500;

  function sanitizeFilenamePart(value) {
    return String(value || "")
      .trim()
      .replace(/[\\/:*?"<>|]/g, "_")
      .replace(/\s+/g, " ")
      .replace(/^\.+$/, "")
      .slice(0, 120);
  }

  function inferExtension(audioUrl) {
    try {
      const parsedUrl = new URL(audioUrl);
      const pathExtension = parsedUrl.pathname.match(/\.(mp3|m4a|mp4|flac|wav|ogg|aac|opus)$/i)?.[0];
      if (pathExtension) {
        return pathExtension.toLowerCase();
      }

      const mimeType = parsedUrl.searchParams.get("mime_type") || "";
      if (/audio_mp4|audio\/mp4|mp4/i.test(mimeType)) {
        return ".m4a";
      }
      if (/mpeg|mp3/i.test(mimeType)) {
        return ".mp3";
      }
      if (/flac/i.test(mimeType)) {
        return ".flac";
      }
      if (/wav/i.test(mimeType)) {
        return ".wav";
      }
      if (/ogg/i.test(mimeType)) {
        return ".ogg";
      }
    } catch {
      // Fall through to the default extension.
    }

    return ".m4a";
  }

  function buildFilename(track) {
    const artistName = sanitizeFilenamePart(track.artistName) || "Unknown Artist";
    const trackName = sanitizeFilenamePart(track.trackName) || "Unknown Track";
    const audioUrl = track.url;
    const extension = inferExtension(audioUrl);
    return `${artistName}-${trackName}${extension}`;
  }

  function readTrack(pageWindow) {
    const option =
      pageWindow._ROUTER_DATA?.loaderData?.track_page?.audioWithLyricsOption;

    if (!option?.url) {
      return null;
    }

    return {
      url: option.url,
      artistName: option.artistName || "Unknown Artist",
      trackName: option.trackName || "Unknown Track",
    };
  }

  function createDownloadButton(onClick) {
    const button = document.createElement("span");
    button.id = DOWNLOAD_BUTTON_ID;
    button.textContent = "立即下载";
    button.title = "下载当前歌曲";
    button.style.cssText = [
      "display:inline-flex",
      "align-items:center",
      "margin-left:12px",
      "padding:4px 10px",
      "border-radius:4px",
      "background:#ff2c55",
      "color:#fff",
      "font-size:14px",
      "font-weight:500",
      "line-height:20px",
      "cursor:pointer",
      "vertical-align:middle",
      "user-select:none",
    ].join(";");

    button.addEventListener("click", (event) => {
      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();
      onClick(event);
    });

    return button;
  }

  function installDownloadButton(options) {
    const {
      onDownload,
      pageWindow = globalScope,
      maxAttempts = DEFAULT_MAX_ATTEMPTS,
      intervalMs = DEFAULT_INTERVAL_MS,
      preventDuplicate = false,
    } = options;
    const seenAudioUrls = new Set();
    let attempts = 0;
    let scheduled = false;
    let retryTimer = null;

    function handleClick() {
      const track = readTrack(pageWindow);
      if (!track) {
        globalScope.alert("音频信息尚未加载，请稍后再试。");
        return;
      }

      if (preventDuplicate && seenAudioUrls.has(track.url)) {
        return;
      }

      seenAudioUrls.add(track.url);
      onDownload(track);
    }

    function findTitle() {
      return document.querySelector(".track-title h1") || document.querySelector("h1");
    }

    function ensureDownloadButton() {
      scheduled = false;

      const title = findTitle();
      const existingButton = document.getElementById(DOWNLOAD_BUTTON_ID);

      if (!title) {
        existingButton?.remove();
        return false;
      }

      if (existingButton?.previousElementSibling === title) {
        return true;
      }

      existingButton?.remove();
      title.insertAdjacentElement("afterend", createDownloadButton(handleClick));
      return true;
    }

    function scheduleEnsureDownloadButton() {
      if (scheduled) {
        return;
      }

      scheduled = true;
      globalScope.setTimeout(ensureDownloadButton, 50);
    }

    const observer = new MutationObserver(scheduleEnsureDownloadButton);
    observer.observe(document.documentElement || document, {
      childList: true,
      subtree: true,
    });

    function retryInsertDownloadButton() {
      attempts += 1;

      if (ensureDownloadButton() || attempts >= maxAttempts) {
        globalScope.clearInterval(retryTimer);
      }
    }

    retryTimer = globalScope.setInterval(retryInsertDownloadButton, intervalMs);
    retryInsertDownloadButton();

    return {
      disconnect() {
        observer.disconnect();
        globalScope.clearInterval(retryTimer);
      },
      refresh: ensureDownloadButton,
    };
  }

  globalScope.SodaMusicDownloadUtils = {
    sanitizeFilenamePart,
    inferExtension,
    buildFilename,
    readTrack,
    installDownloadButton,
  };
})(globalThis);


  const pageWindow = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;
  const { buildFilename, installDownloadButton } = globalThis.SodaMusicDownloadUtils;
  const NOTICE_SHOWN_KEY = "soda_music_download_install_notice_shown";
  const INSTALL_NOTICE_HTML = `<!doctype html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>汽水音乐下载</title>
</head>

<body>
  <main>
    <h1>Soda(qishui) Music Download / 汽水音乐下载</h1>
    <p>插件安装完成。打开汽水音乐APP，复制分享链接，浏览器打开分享页后，歌曲名 右侧会出现红色“立即下载”按钮。</p>
    <div style="display: flex; gap: 24px; align-items: flex-start;">
      <div style="flex: 1;">
        <p> <img src="https://i.postimg.cc/zG6rMVP6/Angel.webp" alt="测试页面" width="240"> </p>
        <p>测试地址1: <a href="https://music.douyin.com/qishui/share/track?track_id=7645128283450984475">https://music.douyin.com/qishui/share/track?track_id=7645128283450984475</a></p>
        <p>测试地址2: <a href="https://www.qishui.com/share/track?track_id=7645128283450984475">https://www.qishui.com/share/track?track_id=7645128283450984475</a></p>
      </div>

      <div style="flex: 1;">
        <h2>免责声明</h2>
        <p>本项目纯粹用于研究插件开发机制和原理，下载的音乐质量真的差劲，只能听个响。</p>
        <h2>支持作者</h2>
        <p style="color: red;">开源不易，善良的好人们，行行好施舍点银子给我买包烟吧，一块两块不嫌少三块四块会更好，赠人香烟手有余香。——by：爱抽烟的人</p>
        <p>
          <img src="https://i.postimg.cc/mk8vWPht/Ali-Pay.webp" alt="支付宝收款码" width="220">
          <img src="https://i.postimg.cc/0jcT1zrz/We-Chat-Pay.webp" alt="微信收款码" width="220">
        </p>
        <h2><a href="https://github.com/galaxy-sea/Soda-Music-Download/issues/new">BUG修复，问题访问，点这里</a></h2>
      </div>
    </div>
  </main>
</body>

</html>`;

  function openInstallNoticeOnce() {
    if (typeof GM_getValue !== "function" || typeof GM_setValue !== "function") {
      return;
    }

    if (GM_getValue(NOTICE_SHOWN_KEY, false)) {
      return;
    }

    GM_setValue(NOTICE_SHOWN_KEY, true);

    const noticeUrl = URL.createObjectURL(new Blob([INSTALL_NOTICE_HTML], { type: "text/html" }));

    if (typeof GM_openInTab === "function") {
      GM_openInTab(noticeUrl, { active: true, insert: true });
      return;
    }

    window.open(noticeUrl, "_blank", "noopener,noreferrer");
  }

  function download(track) {
    if (typeof GM_download !== "function") {
      console.error("[Soda(qishui) Music Download] GM_download is unavailable.");
      return;
    }

    GM_download({
      url: track.url,
      name: buildFilename(track),
      saveAs: false,
      onerror: (error) => {
        console.error("[Soda(qishui) Music Download] Download failed:", error);
      },
    });
  }

  installDownloadButton({
    pageWindow,
    preventDuplicate: true,
    onDownload: download,
  });

  openInstallNoticeOnce();
})();
